collection = {
   "cities":[
      {
         "name":"Vancouver",
         "object":{
            "coord":{
               "lon":-123.1193,
               "lat":49.2497
            },
            "weather":[
               {
                  "id":801,
                  "main":"Clouds",
                  "description":"few clouds",
                  "icon":"02d"
               }
            ],
            "base":"stations",
            "main":{
               "temp":10.7,
               "feels_like":295.51,
               "temp_min":290.72,
               "temp_max":299.8,
               "pressure":1012,
               "humidity":63
            },
            "visibility":10000,
            "wind":{
               "speed":1.79,
               "deg":314,
               "gust":7.15
            },
            "clouds":{
               "all":20
            },
            "dt":1624294720,
            "sys":{
               "type":2,
               "id":2011597,
               "country":"CA",
               "sunrise":1624277221,
               "sunset":1624335698
            },
            "timezone":-25200,
            "id":6173331,
            "name":"Vancouver",
            "cod":200
         }
      },
      {
         "name":"Toronto",
         "object":{
            "coord":{
               "lon":-123.1193,
               "lat":49.2497
            },
            "weather":[
               {
                  "id":801,
                  "main":"Clouds",
                  "description":"few clouds",
                  "icon":"02d"
               }
            ],
            "base":"stations",
            "main":{
               "temp":295.57,
               "feels_like":295.51,
               "temp_min":290.72,
               "temp_max":299.8,
               "pressure":1012,
               "humidity":63
            },
            "visibility":10000,
            "wind":{
               "speed":1.79,
               "deg":314,
               "gust":7.15
            },
            "clouds":{
               "all":20
            },
            "dt":1624294720,
            "sys":{
               "type":2,
               "id":2011597,
               "country":"CA",
               "sunrise":1624277221,
               "sunset":1624335698
            },
            "timezone":-25200,
            "id":6173331,
            "name":"Toronto",
            "cod":200
         }
      }
   ]
}

module.exports = collection
